#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "my_djangoapp"
name = "My Django App"
description.en = "Custom Django app installer"
description.fr = "Installateur d'aplication Django custom"

version = "1.0~ynh1"

maintainers = ["DeMiro5001"]

[upstream]
license = "GPL-3.0-only"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.project]
    ask.en = "Locate your django project archive : either local or remote (zip or tar.gz)"
    ask.fr = "Localisez votre archive de projet django : local ou distante (zip ou tar.gz)"
    type = "text"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

    [install.db_engine]
    ask.en = "What database engine do you want to use ?"
    ask.fr = "Quelle base de données voulez-vous utiliser ?"
    type = "select"
    choices = ["sqlite", "postgresql"]
    default = "sqlite"
    help = """Add this DB block to the app configuration file :
```
                # settings.py
                DB_ENGINE = env('DB_ENGINE', default='sqlite3')

                if DB_ENGINE == 'postgresql':
                    DATABASES = {
                        'default': {
                            'ENGINE': 'django.db.backends.postgresql',
                            'NAME': env('DB_NAME', default='scientevent_db'),
                            'USER': env('DB_USER', default=''),
                            'PASSWORD': env('DB_PASSWORD', default=''),
                            'HOST': env('DB_HOST', default='localhost'),
                            'PORT': env('DB_PORT', default=''),
                        }
                    }
                else:
                    # Default to SQLite
                    DATABASES = {
                        'default': {
                            'ENGINE': 'django.db.backends.sqlite3',
                            'NAME': BASE_DIR / env('DB_NAME', default='db.sqlite3'),
                        }
                    }
```
    """

    [install.use_redis]
    ask.en = "Activate redis server"
    ask.fr = "Activer le serveur redis"
    type = "boolean"
    default = true
    help = """Add redis support to the app configuration file :
```
                # settings.py
                CACHES = {
                    'default': {
                        'BACKEND': 'django_redis.cache.RedisCache',
                        'LOCATION': os.getenv('REDIS_URL'),
                        'OPTIONS': {
                            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
                            'SOCKET_CONNECT_TIMEOUT': 5,
                            'SOCKET_TIMEOUT': 5,
                            'CONNECTION_POOL_KWARGS': {'max_connections': 100},
                        },
                        'KEY_PREFIX': '__APP__',
                    }
                }

                # Cache templates
                TEMPLATES = [{
                    'BACKEND': 'django.template.backends.django.DjangoTemplates',
                    'DIRS': [],
                    'APP_DIRS': True,
                    'OPTIONS': {
                        'context_processors': [...],
                        'loaders': [
                            ('django.template.loaders.cached.Loader', [
                                'django.template.loaders.filesystem.Loader',
                                'django.template.loaders.app_directories.Loader',
                            ]),
                        ],
                    },
                }]
```
    """

    [install.use_celery]
    ask.en = "Activate celery broker"
    ask.fr = "Activer le broker celery"
    type = "boolean"
    default = false
    help = """Add celery support to the app configuration file :
```
        # settings.py
        INSTALLED_APPS += [
        ...............OTHERS...............
            'django_celery_results',
            'django_celery_beat',
        ]

        # Celery Configuration
        CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL')
        CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND')
        CELERY_ACCEPT_CONTENT = ['application/json']
        CELERY_TASK_SERIALIZER = 'json'
        CELERY_RESULT_SERIALIZER = 'json'
        CELERY_TIMEZONE = 'UTC'
        CELERY_TASK_TRACK_STARTED = True
        CELERY_TASK_TIME_LIMIT = 30 * 60
        CELERY_RESULT_EXPIRES = 3600
        CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
```
        """

[resources]

    [resources.system_user]
    allow_email = true
    mail_user = 'noreply'

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    flower.url = "/flower"
    flower.allowed = "admins"
    flower.show_tile = true

    [resources.ports]

    [resources.apt]
    packages = "postgresql, postgresql-contrib, libpq-dev, python3-pip, python3-venv, python3-dev, redis-server"

    [resources.database]
    type = "postgresql"
