#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    args.project = "https://github.com/DeMiro5001/linkdir/archive/refs/tags/v1.1.0.tar.gz"
    args.db_engine = "sqlite3"
    # args.multisite = 0

## This is an additional test suite
# [some_additional_testsuite]

    ## On additional tests suites, you can decide to run only specific tests

    # only = ["install.subdir"]

    # args.language = "en_GB"
    # args.multisite = 1
