#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app-gunicorn" --action="stop"

if [ "$use_celery" -eq 1 ]; then
    ynh_systemctl --service="$app-celery" --action="stop"
    ynh_systemctl --service="$app-celery-beat" --action="stop"
    ynh_systemctl --service="$app-flower" --action="stop"
fi

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================

mail_user="noreply" 

    if [ -f "$install_dir/.env.example" ]; then
        ynh_config_add --template="$install_dir/.env.example" --destination="$install_dir/.env"
    else
        
        if [ "$db_engine" = "postgresql" ]; then
            ynh_config_add --template=".env" --destination="$install_dir/.env"
        
        elif [ "$db_engine" = "sqlite" ]; then
            ynh_config_add --template=".env.sqlite" --destination="$install_dir/.env"
        fi
    
    fi

chmod 400 "$install_dir/.env"
chown "$app:$app" "$install_dir/.env"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app-gunicorn" --action="start"

if [ "$use_celery" -eq 1 ]; then
    ynh_systemctl --service="$app-celery" --action="start"
    ynh_systemctl --service="$app-celery-beat" --action="start"
    ynh_systemctl --service="$app-flower" --action="start"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
