#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

secret_key=$(ynh_string_random --length=64)
ynh_app_setting_set --key=secret_key --value=$secret_key

admin_mail=$(ynh_user_get_info --username=$admin --key=mail)
ynh_app_setting_set --key=admin_mail --value=$admin_mail

timezone="$(timedatectl show --value --property=Timezone)"
ynh_app_setting_set --key=timezone --value=$timezone

redis_db=$(ynh_redis_get_free_db)
ynh_app_setting_set --app=$app --key=redis_db --value=$redis_db
redis_lock "redis_db" 

celery_broker_db=$(ynh_redis_get_free_db)
ynh_app_setting_set --app=$app --key=celery_broker_db --value=$celery_broker_db
redis_lock "celery_broker_db"

celery_result_db=$(ynh_redis_get_free_db)
ynh_app_setting_set --app=$app --key=celery_result_db --value=$celery_result_db

redis_unlock "redis_db"
redis_unlock "celery_broker_db"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

pushd $install_dir
    extract_project $project

    # .env
    if $db_engine = "postgresql"; then
    ynh_config_add --template=".env" --destination="$install_dir/.env"
    fi

    if $db_engine = "sqlite"; then
    ynh_config_add --template=".env.sqlite" --destination="$install_dir/.env"
    fi

    chmod 400 "$install_dir/.env"
    chown "$app:$app" "$install_dir/.env"

    python -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
    python manage.py migrate
    python manage.py collectstatic --noinput
    DJANGO_SUPERUSER_USERNAME=$admin DJANGO_SUPERUSER_EMAIL=$admin_email DJANGO_SUPERUSER_PASSWORD=$password python manage.py createsuperuser --noinput
    deactivate
popd

chown -R "$app:$app" "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="$app-gunicorn" --template="gunicorn.service"
yunohost service add "$app-gunicorn" --description="Gunicorn for $app" --log="/var/log/$app/$app-gunicorn.log"

if use_celery; then
    ynh_config_add_systemd --service="$app-celery" --template="celery.service"
    ynh_config_add_systemd --service="$app-celery-beat" --template="celery-beat.service"
    ynh_config_add_systemd --service="$app-flower" --template="flower.service"
    yunohost service add "$app-celery" --description="Celery for $app" --log="/var/log/$app/$app-celery.log"
    yunohost service add "$app-celery-beat" --description="Celery beat for $app" --log="/var/log/$app/$app-celery-beat.log"
    yunohost service add "$app-flower" --description="Flower for $app" --log="/var/log/$app/$app-flower.log"
fi

ynh_config_add_logrotate

ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app-gunicorn" --action="start"

if use_celery; then
    ynh_systemctl --service="$app-celery" --action="start"
    ynh_systemctl --service="$app-celery-beat" --action="start"
    ynh_systemctl --service="$app-flower" --action="start"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
