#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

ynh_config_remove_fail2ban

ynh_config_remove_logrotate

yunohost service remove "$app-gunicorn"
ynh_config_remove_systemd "$app-gunicorn"

if use_celery
    yunohost service remove "$app-celery"
    yunohost service remove "$app-celery-beat"
    yunohost service remove "$app-flower"
    ynh_config_remove_systemd "$app-celery"
    ynh_config_remove_systemd "$app-celery-beat"
    ynh_config_remove_systemd "$app-flower"
fi

ynh_config_remove_nginx

ynh_redis_remove_db $redis_db
ynh_redis_remove_db $celery_broker_db
ynh_redis_remove_db $celery_result_db

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
