#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"
chown -R "$app:$app" "$install_dir"

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "$data_dir"
chown -R "$app:$app" "$data_dir"

#=================================================
# RESTORE THE MYSQL DATABASE
#=================================================
ynh_script_progression "Restoring the Podstgresql database..."

if $db_engine = "postgresql"; then
ynh_psql_db_shell < ./db.sql
fi

#=================================================
# RESTORE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app-gunicorn.service"
systemctl enable "$app-gunicorn.service" --quiet
yunohost service add "$app-gunicorn" --description="Gunicorn for $app" --log="/var/log/$app/$app-gunicorn.log"

if [ "use_celery" ]; then
    ynh_restore "/etc/systemd/system/$app-celery.service"
    systemctl enable "$app-celery.service" --quiet
    yunohost service add "$app-celery" --description="Celery for $app" --log="/var/log/$app/$app-celery.log"

    ynh_restore "/etc/systemd/system/$app-celery-beat.service"
    systemctl enable "$app-celery-beat.service" --quiet
    yunohost service add "$app-celery-beat" --description="Celery beat for $app" --log="/var/log/$app/$app-celery-beat.log"

    ynh_restore "/etc/systemd/system/$app-flower.service"
    systemctl enable "$app-flower.service" --quiet
    yunohost service add "$app-flower" --description="Flower for $app" --log="/var/log/$app/$app-flower.log"
fi

ynh_restore "/etc/logrotate.d/$app"

# ynh_restore "/etc/fail2ban/jail.d/$app.conf"
# ynh_restore "/etc/fail2ban/filter.d/$app.conf"
# ynh_systemctl --action=restart --service=fail2ban

#=================================================
# RESTORE VARIOUS FILES
#=================================================

ynh_restore "/var/log/$app/"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."


ynh_systemctl ---service="$app-gunicorn" --action="start"

if [ "use_celery" ]; then
    ynh_systemctl --service="$app-celery" --action="start"
    ynh_systemctl --service="$app-celery-beat" --action="start"
    ynh_systemctl --service="$app-flower" --action="start"
fi

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
