#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

secret_key=$(ynh_app_setting_get --app=$app --key=secret_key)
admin_mail=$(ynh_app_setting_get --app=$app --key=admin_mail)
timezone=$(ynh_app_setting_get --app=$app --key=timezone)
redis_db=$(ynh_app_setting_get --app=$app --key=secret_key)
celery_broker_db=$(ynh_app_setting_get --app=$app --key=secret_key)
celery_result_db=$(ynh_app_setting_get --app=$app --key=secret_key)

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app-gunicorn" --action="stop"

if use_celery
    ynh_systemctl --service="$app-celery" --action="stop"
    ynh_systemctl --service="$app-celery-beat" --action="stop"
    ynh_systemctl --service="$app-flower" --action="stop"
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

extract_project $project

pushd $install_dir
    source venv/bin/activate
    pip install --upgrade -r requirements.txt
    python manage.py migrate
    python manage.py collectstatic --noinput
    deactivate
popd

chown -R "$app:$app" "$install_dir"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."


if db_engine = "postgresql"
ynh_config_add --template=".env" --destination="$install_dir/.env"
fi

if db_engine = "sqlite3"
ynh_config_add --template=".env" --destination="$install_dir/.env.sqlite"
fi

chmod 400 "$install_dir/.env"
chown "$app:$app" "$install_dir/.env"

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="$app-gunicorn" --template="gunicorn.service"
yunohost service add "$app-gunicorn" --description="Gunicorn for $app" --log="/var/log/$app/$app-gunicorn.log"

if use_celery
    ynh_config_add_systemd --service="$app-celery" --template="celery.service"
    ynh_config_add_systemd --service="$app-celery-beat" --template="celery-beat.service"
    ynh_config_add_systemd --service="$app-flower" --template="flower.service"
    yunohost service add "$app-celery" --description="Celery for $app" --log="/var/log/$app/$app-celery.log"
    yunohost service add "$app-celery-beat" --description="Celery beat for $app" --log="/var/log/$app/$app-celery-beat.log"
    yunohost service add "$app-flower" --description="Flower for $app" --log="/var/log/$app/$app-flower.log"
fi

ynh_config_add_logrotate

ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app-gunicorn" --action="start"

if use_celery
    ynh_systemctl --service="$app-celery" --action="start"
    ynh_systemctl --service="$app-celery-beat" --action="start"
    ynh_systemctl --service="$app-flower" --action="start"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
